spring:
  application:
    name: devnest
  datasource:
    url: jdbc:postgresql://localhost:5500/devnest
    username: devnest
    password: devnest
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
